#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=50gb,walltime=00:45:00
#PBS -N DARTS
#PBS -V

set -e
set -x

t1=`jq -r .t1 config.json`

mkdir -p parc
cp key.txt parc/key.txt

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

time singularity exec -e docker://davhunt/darts:1.0.2./segment.py "$t1"
