#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=30gb,walltime=00:30:00
#PBS -N DARTS
#PBS -V

set -e
set -x

t1=`jq -r .t1 config.json`

mkdir -p parc
cp key.txt parc/key.txt

time singularity exec -e docker://davhunt/darts:0.1 ./segment.py "$t1"
